@startuml

start
:获取数据;
split
  :点击修改按钮，
  获取到该仓库的id、海外仓id、仓库分布id和仓库名warehouse_name;
  :将获取到的数据赋给修改仓库表单对象，
  且将海外仓和仓库分布表单项置灰;
  :弹出修改仓库弹窗;
split again
  :点击新增按钮;
  :从localStorage获取海外仓列表数据和仓库分布数据列表;
  :弹出新增表单;
  :选定海外仓以及仓库分布;
end split
repeat
    :输入/修改仓库名称;
  repeat while(表单校验 通过?) is (no) not (yes)
  note right 
    校验规则伪代码
    ====
    //允许中英文，数字，下划线，中划线
    let reg = new RegExp
    ("^[\u4E00-\u9FA5A-Za-z0-9_-]+$")
    //true: 通过校验; false: 未通过校验
    reg.test(str) 
  end note
  if(新增 ?) then (yes)
    :请求"/system/base/warehouse-create"接口;
  else (no)
    :请求"/system/base/warehouse-update"接口;
  endif
  if(请求 成功?) then (yes)
   if(新增 ?) then (yes)
      :current_page = 1;
      :删除overseaLocation变量;
    endif
    :删除overseaLocationOption缓存;
    :获取数据;
    :关闭弹窗;
  else (no)
    :提示出错信息;
  endif
end

@enduml