@startuml

start
:获取数据;
split
  :点击修改，获取到该店铺id和name;
  :将该店铺name赋给修改表单对象;
  :弹出修改店铺弹窗;
split again
  :点击新增店铺按钮;
  :弹出新增店铺弹窗;
end split
 repeat
    :批量输入/修改店铺;
    if(输入的字符串长度 === 1000) then (yes)
      :弹出提示：超出规定字数，请检查最后一项是否被截断;
      :修改输入的店铺;
    endif
  repeat while(表单校验 通过?) is (no) not (yes)
  note right 
    校验规则伪代码
    ====
    //允许英文，数字，下划线，中划线
    var reg = new RegExp
    ('^[A-Za-z0-9_-]+$')  
    //true: 通过校验; false: 未通过校验
    reg.test(str)  
  end note
  if(新增 ?) then (yes)
    :请求"/system/base/shop-create"接口;
  else (no)
    :请求"/system/base/shop-update"接口;
  endif
  if(请求 成功?) then (yes)
    if(存在错误数据 ?) then (yes)
      :将返回的错误数据列表赋给表格对象;
      :弹出错误详情展示弹窗;
    else (no)
      if(新增 ?) then (yes)
        :current_page = 1;
        :删除overseaLocation变量;
      endif
       :删除overseaLocationOption缓存;
      :获取数据;
      :提示成功，关闭弹窗;
      endif
  else (no)
    :提示出错信息;
    stop
  endif
end

@enduml
