@startuml

start
:新增订单信息按钮;
if(logisiticsShopOption 已存在?) then (yes)
  :从localStorage中获取店铺(logisiticsShopOption)下拉选项;
else (no)
  :请求"/option/shop-list"接口;
  if(请求 成功?) then (yes)
    :本地存储logisiticsShopOption;
  else (no)
    :提示出错信息;
    stop
  endif
endif
if(logisiticsPlatformOption 已存在?) then (yes)
  :从localStorage中获取平台(logisiticsPlatformOption)下拉选项;
else (no)
  :请求"/option/platform-list"接口;
  if(请求 成功?) then (yes)
    :本地存储logisiticsPlatformOption;
  else (no)
    :提示出错信息;
    stop
  endif
endif
:弹出新增订单弹窗;
repeat 
fork
  :输入订单号;
fork again
  :选择支付时间;
  :将选定的时间通过时间转化函数，转化为时间戳;
fork again
  :从下拉列表中选择需要的平台和店铺选项;
end fork 
backward: 根据校验信息修改表单项;
repeat while (表单校验 通过?) is (no) not (yes)
note right
  校验规则伪代码
  ====
  //允许英文，数字，中划线
  let reg = new RegExp
  ("^[A-Za-z0-9-]+$")
end note
:请求"/order/create"接口;
if(请求 成功?) then (yes)
  :提示新增成功;
  :关闭弹窗;
else (no)
  :提示出错信息;
endif
end

@enduml