@startuml

start
:勾选需要修改添加标签的运单;
:点击标记为按钮;
:从localStorage中获取logistics option，
并从中获取标签下拉选项;
:从下拉列表中选定某个选项;
:请求"/waybill/label-update"接口;
if(请求 成功?) then (yes)
  :提示更新成功;
  :请求"/waybill/list"接口，更新运单列表;
else (no)
  :提示更新失败;
  stop
endif
end

@enduml