@startuml

start
:勾选需要修改物流商的运单;
:点击修改物流商按钮;
:请求"/option/logistic-supplier-list"接口;
  if(请求 成功?) then (yes)
    :将返回的数据赋给下拉框对象;
  else (no)
    :提示出错信息;
    stop
endif
:弹出修改物流商弹窗;
repeat
  :从下拉列表中选择物流商;
repeat while(表单校验 通过?) is (no) not (yes)
:请求"/waybill/logistic-supplier-update"接口;
if(请求 成功?) then (yes)
  :提示修改成功;
  :请求"/waybill/list"接口，更新运单列表;
  :关闭弹窗;
else (no)
  :提示出错信息;
endif
end

@enduml