@startuml

package "Parent Component" {
  [DailyStatistics]
  [AverageStatistics]
}

package "Child Components" {
  [BaseForm]
  [BaseChart]
  [DailyTable]
  [BaseBreadcrumb]
  [CommonStatistics]
}

package "Descendant Components" {
  [BaseTable]
  [BaseForm]
}

[DailyStatistics]            -->       [BaseBreadcrumb]
[DailyStatistics]            -->       [CommonStatistics]
[AverageStatistics]       -->       [BaseForm]
[AverageStatistics]       -->       [BaseBreadcrumb]
[AverageStatistics]       -->       [BaseChart]
[BaseChart]                  -->       [BaseTable]
[CommonStatistics]      -->       [BaseForm]


@enduml